In [14]:
#upsampling convolution using the nearest neighbour techniques
import numpy as np
from keras import models
from keras.layers import UpSampling2D ,Conv2DTranspose

In [3]:
# taking the 2X2 input from user and converting it to the 4X4 output using the upsampling techniques of nearset one
a=np.array([[1,2],[3,4]])

In [4]:
print(a)

[[1 2]
 [3 4]]


In [5]:
type(a)

numpy.ndarray

In [6]:
#reshaping the input in order to provide the channel depth of 1 to the array
#below codes form 1 3D array 
a=a.reshape((1,2,2,1))

In [7]:
print(a.shape)
print(type(a))
print(a.ndim)

(1, 2, 2, 1)
<class 'numpy.ndarray'>
4


In [8]:
#keras version 2.2.4 is required for the interpolation function of the upsampling function
import keras
keras.__version__

'2.2.4'

In [9]:
#now creating a model to upsample the image
model=models.Sequential()
model.add(UpSampling2D(input_shape=(2,2,1) , interpolation="nearest"))
model.summary()




_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [12]:
a_out=model.predict(a)
print(a_out)

[[[[1.]
   [1.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [4.]
   [4.]]]]


In [13]:
print(a_out.reshape(4,4)) #using the nearest interpolation

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [15]:
#upsamling using Transpose convolution 2d layer
model=models.Sequential()
model.add(Conv2DTranspose(filters=1,kernel_size=(1,1),strides=(2,2), input_shape=(2,2,1)))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_1 (Conv2DTr (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [18]:
#since we are not training the model we will set the weights by ourself
weights = [ np.array([[[[1]]]]), np.array([0])]   #s
model.set_weights(weights)

In [21]:
#making the prediction
a_out=model.predict(a)
print(a_out.reshape(4,4))

[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]
